import type { Metadata } from "next";
import { LegalLayout } from "../page-elements";

export const metadata: Metadata = { title: "Používanie údajov Google | ZevsFlow", description: "Ako ZevsFlow plánuje pristupovať k údajom Google Drive alebo Gmailu a ako možno pripojenie zrušiť." };

export default function GoogleDataPage() {
  return <LegalLayout title="Používanie údajov Google" intro="Táto stránka opisuje plánované zásady Google integrácie. Produkčné oprávnenia budú zverejnené podľa funkcií, ktoré ZevsFlow skutočne spustí.">
    <section><h2>1. Prečo môže ZevsFlow žiadať prístup</h2><p>Google pripojenie je voliteľné a používa sa iba na funkciu, ktorú si používateľ zapne. Príkladom je uloženie vytvoreného dokumentu do Google Drive, výber súboru na spracovanie alebo prevzatie dohodnutých emailových príloh.</p></section>
    <section><h2>2. Plánovaný rozsah</h2><p>Pre Google Drive sa najprv posudzuje oprávnenie <code>https://www.googleapis.com/auth/drive.file</code>, ktoré umožňuje pracovať so súbormi vytvorenými aplikáciou alebo výslovne sprístupnenými používateľom. Široký prístup ku všetkým súborom sa nebude používať bez zdokumentovanej technickej potreby.</p><p>Prístup ku Gmailu sa nebude žiadať, kým nebude presne určený používateľský scenár, minimálny scope, retenčné pravidlá a požiadavky Google verification.</p></section>
    <section><h2>3. Aké údaje sa môžu spracúvať</h2><ul><li>identifikátor Google účtu a stav pripojenia;</li><li>OAuth access a refresh token uložený mimo frontendu;</li><li>identifikátory, názvy a obsah konkrétnych súborov potrebných pre zapnutú funkciu;</li><li>metadáta alebo prílohy konkrétnych správ, iba ak používateľ zapne a oprávni emailový proces;</li><li>technické záznamy bez tokenov a zbytočného obsahu dokumentov.</li></ul></section>
    <section><h2>4. Ako sa údaje používajú</h2><p>Google údaje sa používajú výlučne na poskytnutie používateľom viditeľnej funkcie, jej zabezpečenie, údržbu a podporu. ZevsFlow ich nebude predávať, používať na cielenú reklamu ani na trénovanie všeobecných AI modelov.</p><p>Ak konkrétna úloha vyžaduje AI spracovanie obsahu, rozsah, poskytovateľ a režim prenosu musia byť používateľovi alebo firemnému klientovi oznámené pred aktiváciou.</p></section>
    <section><h2>5. Ukladanie a ochrana tokenov</h2><p>Autorizačný kód sa má vymieňať na serveri. Tokeny sa nesmú objaviť v URL, klientskom JavaScripte ani aplikačných logoch. Pri spravovanom modeli sa refresh token uloží šifrovane a prístup k nemu sa obmedzí na službu, ktorá vykonáva povolenú integráciu.</p></section>
    <section><h2>6. Zdieľanie</h2><p>Google údaje sa neposkytujú tretím stranám na ich vlastný marketing. Sprístupnenie technickému poskytovateľovi je prípustné iba v rozsahu potrebnom na zapnutú funkciu, bezpečnosť alebo podporu a podľa príslušných zmluvných podmienok.</p></section>
    <section><h2>7. Odpojenie Google</h2><p>Používateľ bude môcť odpojiť Google v nastaveniach príslušnej služby. Prístup možno kedykoľvek odvolať aj v nastaveniach Google účtu v časti pripojení tretích strán. Podrobný pracovný postup je na stránke <a href="/data-deletion">Vymazanie údajov</a>.</p></section>
    <section><h2>8. Stav pripravenosti</h2><p>ZevsFlow zatiaľ nespúšťa verejné produkčné OAuth pripojenie cez tento web. Pred spustením sa musia zosúladiť vlastný overený doménový názov, OAuth branding, skutočné scopes, obrazovka odpojenia, retenčná politika a end-to-end demonštrácia.</p></section>
  </LegalLayout>;
}
