import type { Metadata } from "next";
import { LegalLayout } from "../page-elements";

export const metadata: Metadata = { title: "Ochrana súkromia | ZevsFlow", description: "Informácie o spracúvaní osobných údajov pri webe, žiadosti o pilot a službách ZevsFlow." };

export default function PrivacyPage() {
  return <LegalLayout title="Ochrana súkromia" intro="Táto stránka vysvetľuje spracúvanie osobných údajov pri používaní webu, obchodnej komunikácii, žiadosti o pilot, zákazkových implementáciách a prípadnej spravovanej službe ZevsFlow.">
    <section><h2>1. Prevádzkovateľ</h2><p><strong>Zevs s. r. o.</strong>, IČO: 56055552, sídlo: Karpatské námestie 7770/10A, 831 06 Bratislava – mestská časť Rača, Slovenská republika.</p><p>Kontaktný email pre obchodné otázky, podporu, súkromie a vymazanie údajov: <a href="mailto:officezevs2024@gmail.com">officezevs2024@gmail.com</a>.</p></section>
    <section><h2>2. Režimy spracúvania</h2><h3>Web a obchodná komunikácia</h3><p>Zevs s. r. o. spracúva údaje potrebné na odpoveď na dopyt, prípravu ponuky, uzatvorenie zmluvy, podporu a ochranu služby.</p><h3>Žiadosť o pilot</h3><p>Formulár na stránke <a href="/pilot">Pilot za 200 €</a> prijíma typ podnikania, názov firmy, oblasť podnikania, opis jedného procesu, súčasný spôsob práce, očakávaný výsledok a kontaktné údaje. Formulár neprijíma súbory, heslá, API kľúče ani OAuth tokeny.</p><p>Údaje sa po serverovej kontrole odošlú do firemnej Gmail schránky. ZevsFlow pre tieto žiadosti nevytvára samostatnú databázu kontaktov. Bezpečnostné overenie formulára zabezpečuje Cloudflare Turnstile.</p><h3>Riešenie na infraštruktúre klienta</h3><p>Ak asistent beží výlučne u klienta, centrálne systémy ZevsFlow nemusia prijímať jeho produkčné dokumenty. Pri inštalácii, podpore alebo diagnostike však môže vzniknúť dočasný a dohodnutý prístup.</p><h3>Spravovaná služba</h3><p>Pri spravovanej službe môže ZevsFlow spracúvať údaje účtu, technické záznamy, integračné tokeny, dokumenty a údaje obsiahnuté v používateľom zapnutých procesoch. Presný rozsah musí byť uvedený v ponuke a zodpovedať skutočne spusteným funkciám.</p></section>
    <section><h2>3. Kategórie údajov</h2><ul><li>kontaktné a identifikačné údaje používateľa alebo firmy;</li><li>typ podnikania, oblasť činnosti a názov firmy uvedený v žiadosti;</li><li>opis procesu, súčasného pracovného postupu a očakávaného výsledku;</li><li>obsah dopytu, podpory a zmluvnej komunikácie;</li><li>technické a bezpečnostné údaje potrebné na ochranu formulára a služby;</li><li>údaje OAuth pripojenia a stav integrácie, ak používateľ zapne konkrétnu integráciu;</li><li>dokumenty, hlasové alebo textové pokyny a štruktúrované výsledky, ak ich obsahuje dohodnutá funkcia.</li></ul></section>
    <section><h2>4. Účely a právne základy</h2><ul><li>odpoveď na dopyt a posúdenie žiadosti o pilot – kroky pred uzatvorením zmluvy;</li><li>príprava ponuky, dodanie, prevádzka a podpora služby – kroky pred uzatvorením zmluvy alebo plnenie zmluvy;</li><li>účtovníctvo a zákonné povinnosti – splnenie právnej povinnosti;</li><li>ochrana formulára a služby, prevencia zneužitia a riešenie incidentov – oprávnený záujem, ak nad ním neprevažujú práva dotknutej osoby;</li><li>nepovinná analytika alebo marketing – iba na základe samostatného súhlasu, ak sa zavedú.</li></ul></section>
    <section><h2>5. Príjemcovia a poskytovatelia</h2><p>Pri prevádzke webu a formulára sa používajú služby Cloudflare, Inc. na hosting, bezpečnostné overenie Turnstile a doručenie správy, a služby Google na firemnú Gmail schránku. Pri konkrétnom zákazkovom riešení môžu byť podľa dohody použité ďalšie služby, napríklad úložisko, Google API alebo vybraný AI poskytovateľ. Ich presný rozsah musí zodpovedať skutočne zapnutej funkcii a dohode s klientom.</p></section>
    <section><h2>6. Uchovávanie</h2><p>Žiadosť o pilot sa uchováva vo firemnej emailovej komunikácii iba počas obdobia potrebného na vybavenie dopytu, prípravu ponuky, nadväzujúcu obchodnú komunikáciu a ochranu právnych nárokov. Formulár nevytvára samostatnú aplikačnú databázu žiadostí. Údaje zo zákazkových riešení sa uchovávajú podľa zmluvy, zákonných povinností a pokynov klienta.</p></section>
    <section><h2>7. Práva dotknutých osôb</h2><p>Podľa okolností môžete žiadať prístup, opravu, vymazanie, obmedzenie spracúvania, prenosnosť alebo namietať proti spracúvaniu. Súhlas môžete kedykoľvek odvolať bez vplyvu na zákonnosť pred odvolaním. Máte tiež právo podať sťažnosť Úradu na ochranu osobných údajov Slovenskej republiky.</p></section>
    <section><h2>8. Automatizované rozhodovanie</h2><p>O prijatí pilotu nerozhoduje formulár automaticky. Odoslanie žiadosti nevytvára objednávku, zmluvu, faktúru ani platobnú povinnosť. ZevsFlow nie je navrhnutý na výlučne automatizované rozhodnutia s právnymi alebo podobne významnými účinkami.</p></section>
    <section><h2>9. Google údaje a vymazanie</h2><p>Podrobnosti o integráciách sú uvedené na stránkach <a href="/google-data">Používanie údajov Google</a> a <a href="/data-deletion">Vymazanie údajov</a>.</p></section>
  </LegalLayout>;
}
