import type { Metadata } from "next";
import { LegalLayout } from "../page-elements";

export const metadata: Metadata = { title: "Ochrana súkromia | ZevsFlow", description: "Pracovný návrh informácií o spracúvaní osobných údajov službou ZevsFlow." };

export default function PrivacyPage() {
  return <LegalLayout title="Ochrana súkromia" intro="Táto stránka vysvetľuje plánovaný spôsob spracúvania osobných údajov pri webe, komunikácii, zákazkových implementáciách a budúcej spravovanej službe ZevsFlow.">
    <section><h2>1. Prevádzkovateľ</h2><p><strong>Zevs s. r. o.</strong>, IČO: 56055552, sídlo: Karpatské námestie 7770/10A, 831 06 Bratislava – mestská časť Rača, Slovenská republika.</p><p>Kontaktný email pre tento pracovný náhľad: <a href="mailto:officezevs2024@gmail.com">officezevs2024@gmail.com</a>. Samostatné adresy pre podporu a súkromie budú zverejnené pred verejným spustením.</p></section>
    <section><h2>2. Režimy spracúvania</h2><h3>Web a obchodná komunikácia</h3><p>Zevs s. r. o. spracúva údaje potrebné na odpoveď na dopyt, prípravu ponuky, uzatvorenie zmluvy, podporu a ochranu služby.</p><h3>Riešenie na infraštruktúre klienta</h3><p>Ak asistent beží výlučne u klienta, centrálne systémy ZevsFlow nemusia prijímať jeho produkčné dokumenty. Pri inštalácii, podpore alebo diagnostike však môže vzniknúť dočasný a dohodnutý prístup.</p><h3>Spravovaná služba</h3><p>Pri budúcej spravovanej službe môže ZevsFlow spracúvať údaje účtu, technické záznamy, integračné tokeny, dokumenty a údaje obsiahnuté v používateľom zapnutých procesoch. Presný rozsah musí zodpovedať skutočne spusteným funkciám.</p></section>
    <section><h2>3. Kategórie údajov</h2><ul><li>kontaktné a identifikačné údaje používateľa alebo firmy;</li><li>obsah dopytu, podpory a zmluvnej komunikácie;</li><li>technické a bezpečnostné logy v nevyhnutnom rozsahu;</li><li>údaje OAuth pripojenia a stav integrácie;</li><li>dokumenty, hlasové alebo textové pokyny a štruktúrované výsledky, ak ich obsahuje zapnutá funkcia;</li><li>fakturačné a platobné identifikátory, ak sa neskôr spustí platená online služba.</li></ul></section>
    <section><h2>4. Účely a právne základy</h2><ul><li>odpoveď na dopyt a príprava riešenia – kroky pred uzatvorením zmluvy;</li><li>dodanie, prevádzka a podpora služby – plnenie zmluvy;</li><li>účtovníctvo a zákonné povinnosti – splnenie právnej povinnosti;</li><li>ochrana služby, prevencia zneužitia a riešenie incidentov – oprávnený záujem, ak nad ním neprevažujú práva dotknutej osoby;</li><li>nepovinná analytika alebo marketing – iba na základe samostatného súhlasu, ak sa vôbec zavedú.</li></ul></section>
    <section><h2>5. Príjemcovia a poskytovatelia</h2><p>Údaje môžu byť sprístupnené iba poskytovateľom potrebným pre dohodnutú funkciu, napríklad hostingu, emailu, úložiska, platieb, Google API alebo vybranému AI poskytovateľovi. Produkčný zoznam subprocessors, krajiny spracúvania a mechanizmy prípadného prenosu mimo EHP sa doplnia pred spustením spravovanej služby.</p></section>
    <section><h2>6. Uchovávanie</h2><p>Lehoty sa určia podľa typu služby, zmluvy, zákonných povinností a pokynov klienta. Kontaktné dopyty sa nemajú uchovávať dlhšie, než je potrebné na komunikáciu; bezpečnostné logy len po obmedzený čas; Google token do odpojenia integrácie alebo zániku účtu. Produkčná retenčná tabuľka vrátane záloh musí byť schválená pred verejným SaaS spustením.</p></section>
    <section><h2>7. Práva dotknutých osôb</h2><p>Podľa okolností môžete žiadať prístup, opravu, vymazanie, obmedzenie spracúvania, prenosnosť alebo namietať proti spracúvaniu. Súhlas môžete kedykoľvek odvolať bez vplyvu na zákonnosť pred odvolaním. Máte tiež právo podať sťažnosť Úradu na ochranu osobných údajov Slovenskej republiky.</p></section>
    <section><h2>8. Automatizované rozhodovanie</h2><p>ZevsFlow nie je navrhnutý na výlučne automatizované rozhodnutia s právnymi alebo podobne významnými účinkami. Dôležité zapisujúce kroky majú byť kontrolované a potvrdzované používateľom podľa nastaveného procesu.</p></section>
    <section><h2>9. Google údaje a vymazanie</h2><p>Podrobnosti sú uvedené na stránkach <a href="/google-data">Používanie údajov Google</a> a <a href="/data-deletion">Vymazanie údajov</a>.</p></section>
  </LegalLayout>;
}
